name: Keploy API Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./server
        run: npm install

      - name: Create .env from GitHub Secrets
        working-directory: ./server
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Start Server in Background
        working-directory: ./server
        run: nohup npm start > server.log 2>&1 &

      - name: Wait for Server to be Ready
        run: |
          echo "Waiting for server to start..."
          for i in {1..15}; do
            if curl -s http://localhost:5000/api/books; then
              echo "✅ Server is up!"
              break
            fi
            echo "⏳ Retrying in 2 seconds..."
            sleep 2
          done

      - name: Install Keploy CLI
        run: curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Tests
        working-directory: ./server
        run: |
          export KEPLOY_API_KEY=8+S7+Na7096XO+8UGw==
          export PATH=$HOME/.keploy/bin:$PATH
          keploy test-suite --app=00a2539a-bef0-48fa-ba54-66855e176193 --base-path=http://localhost:5000/api/books --cloud
